name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run tests (unit + api + bdd)
        run: |
          chmod +x mvnw
          ./mvnw -B -Dtest="*ServiceTest,*ApiTest,CucumberTestRunner" test

      - name: Build JAR
        run: ./mvnw -B -DskipTests package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

      - name: Print surefire reports (on failure)
        if: failure()
        run: |
          echo "---- Surefire TXT ----"
          if ls target/surefire-reports/*.txt 1> /dev/null 2>&1; then
            for f in target/surefire-reports/*.txt; do
              echo "FILE: $f"
              echo "----------------------"
              cat "$f"
              echo
            done
          fi

      # 5. SonarCloud analysis (main branch push)
      - name: SonarCloud Analysis (Push)
        if: github.event_name == 'push'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=KasunWilbagedara_Note_app \
            -Dsonar.organization=KasunWilbagedara \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN

      # 6. SonarCloud analysis (pull request)
      - name: SonarCloud Analysis (Pull Request)
        if: github.event_name == 'pull_request'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PULL_REQUEST_BRANCH: ${{ github.head_ref }}
          PULL_REQUEST_KEY: ${{ github.event.pull_request.number }}
          PULL_REQUEST_BASE: ${{ github.base_ref }}
        run: |
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=KasunWilbagedara_Note_app
            -Dsonar.organization=kasunwilbagedara
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.pullrequest.branch=$PULL_REQUEST_BRANCH \
            -Dsonar.pullrequest.key=$PULL_REQUEST_KEY \
            -Dsonar.pullrequest.base=$PULL_REQUEST_BASE
